### ISSUE TITLE
comparing plotters

### ISSUE THREAD

**Issue by arvinderpalaha** [nickbattam/picamon#1]
need to come up with a test harness that can run two plotter solutions with a common api

**Comment by dmichel76** [comment]
Have compares a Pygame implementation with a Matplotlib implementation.  A lot of useful things come for free with Matplotlib (like colourmaps, scaling, etc.) but performance was bad on a small Raspberry Pi and could not get the figure to be displayed full screen without window decoration. Pygame was a bit more work, but more flexible.
